"""
Cross-Platform Page Object Generator.

Generates Page Objects following the login_page.py pattern:
- Platform detection (Android/iOS)
- Helper methods: _by_id(), _by_text(), _by_text_contains()
- Locators as simple strings (converted at runtime)
- No XPath unless absolutely necessary
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from .page_object_generator import PageObjectGenerator


class CrossPlatformPageGenerator(PageObjectGenerator):
    """Enhanced generator that creates cross-platform page objects."""

    def generate_cross_platform(
        self,
        screen_name: str,
        platform: str = "android",
        update: bool = False,
        dry_run: bool = False,
    ) -> str:
        """
        Generate cross-platform Page Object following login_page.py pattern.

        Args:
            screen_name: Name of the screen (e.g., "otp", "settings")
            platform: Target platform ("android" or "ios")
            update: If True, merge with existing file
            dry_run: If True, return code without writing file

        Returns:
            Generated code as string
        """
        # Scan current screen
        elements = self.scan(silent=True)
        if not elements:
            raise ValueError("No elements found on screen. Is the screen fully loaded?")

        # Separate interactive and display elements
        interactive = elements.get("interactive", [])
        display = elements.get("display", [])

        # Generate class name
        class_name = self._to_class_name(screen_name)

        # Generate code
        code = self._generate_header(screen_name, class_name, len(interactive), len(display))
        code += self._generate_imports()
        code += self._generate_class_definition(class_name)
        code += self._generate_screen_timing()
        code += self._generate_locators(interactive, display, platform)
        code += self._generate_init_method(class_name)
        code += self._generate_helper_methods()
        code += self._generate_business_methods(screen_name, interactive, display)

        if dry_run:
            return code

        # Write to file
        output_path = Path(f"src/pages/{screen_name}_page.py")

        if update and output_path.exists():
            # Smart update: merge new locators with existing file
            print(f"🔄 Updating existing file: {output_path}")
            updated_code = self._smart_update_page_object(
                output_path, interactive, display, platform
            )
            output_path.write_text(updated_code)
            print(f"✓ Updated: {output_path}")
            print(f"  - Updated locators for {len(interactive)} interactive elements")
            print(f"  - Updated locators for {len(display)} display elements")
            print("  - ✅ Preserved all custom business logic")
            print("\n⚠️  Review changes and test before using!")
            return updated_code

        output_path.write_text(code)
        print(f"✓ Generated: {output_path}")
        print(f"  - {len(interactive)} interactive elements")
        print(f"  - {len(display)} display elements")
        print(f"  - Platform: {platform}")
        print("\n⚠️  Review and test before using in production!")

        return code

    def _generate_header(
        self, screen_name: str, class_name: str, interactive_count: int, display_count: int
    ) -> str:
        """Generate file docstring header."""
        return f'''"""
{class_name.replace("Page", "")} Page Object for the app Mobile Application.

Auto-generated by CrossPlatformPageGenerator on {datetime.now().strftime("%Y-%m-%d %H:%M")}.
Pattern: login_page.py (cross-platform with helper methods)

Elements found:
- Interactive: {interactive_count} (buttons, inputs, toggles)
- Display: {display_count} (text, labels, headers)

IMPORTANT: Review and customize before use:
- Test on both Android and iOS
- Adjust SCREEN_TIMING baselines after real device testing
- Remove unused locators/methods
- Add custom business logic specific to your flow
"""

'''

    def _generate_imports(self) -> str:
        """Generate import statements."""
        return """import logging

from appium.webdriver.common.appiumby import AppiumBy

from src.pages.base_page import BasePage
from src.reporting.allure_decorators import allure_step_class
from src.reporting.screen_timing import screen_timing_class

logger = logging.getLogger(__name__)


"""

    def _generate_class_definition(self, class_name: str) -> str:
        """Generate class definition with decorators."""
        return f'''@allure_step_class
@screen_timing_class
class {class_name}(BasePage):
    """Page Object for {class_name.replace("Page", "")} screen with automatic Allure reporting."""

'''

    def _generate_screen_timing(self) -> str:
        """Generate SCREEN_TIMING section."""
        return """    # ============================================================================
    # SCREEN TIMING BASELINES - Expected transition times
    # ============================================================================
    # These values are manually calibrated based on real device performance.
    # The decorator automatically tracks and reports actual vs expected times.

    SCREEN_TIMING = {
        "screen_load": {"expected": 3.0, "tolerance": 1.5},  # Adjust after testing
    }

"""

    def _generate_locators(
        self, interactive: list[dict], display: list[dict], platform: str
    ) -> str:
        """Generate locator constants following login_page.py pattern."""
        code = (
            """    # ============================================================================
    # LOCATOR DEFINITIONS — Cross-platform, fast (NO XPath!)
    # Auto-generated from live device scan on """
            + datetime.now().strftime("%Y-%m-%d")
            + """
    #
    # ID-based locators: work on both Android (ID) and iOS (Accessibility ID)
    # Text constants: converted to UiAutomator2 (Android) or NSPredicate (iOS)
    #                 at runtime via _by_text() / _by_text_contains() helpers
    # ============================================================================

"""
        )

        # Interactive elements (ID-based, stored as strings)
        if interactive:
            code += (
                "    # --- Interactive Elements (by resource-id — works on BOTH platforms) ---\n"
            )
            for elem in interactive:
                locator_type = elem.get("locator_type", "")
                locator_value = elem.get("locator", "")
                constant_name = elem.get("constant", "UNKNOWN")

                # Fix invalid Python identifiers
                constant_name = self._fix_constant_name(constant_name)

                if locator_type == "ID" or "resource-id" in locator_value:
                    # Extract ID value
                    id_value = (
                        locator_value.split("'")[1] if "'" in locator_value else locator_value
                    )
                    code += f'    {constant_name} = "{id_value}"\n'
                elif locator_type == "Accessibility ID":
                    acc_value = (
                        locator_value.split("'")[1] if "'" in locator_value else locator_value
                    )
                    code += f'    {constant_name} = "{acc_value}"\n'
            code += "\n"

        # Text/Display elements (stored as text constants)
        if display:
            code += (
                "    # --- Text constants (plain strings — converted per platform by helpers) ---\n"
            )
            text_constants = {}
            for elem in display:
                text = elem.get("text", "").strip()
                if not text or text in ["", "\\ue3c9", "\\ue1b0"]:  # Skip empty/icon texts
                    continue

                # Create constant name from text
                constant_name = self._text_to_constant(text)
                constant_name = self._fix_constant_name(constant_name)

                # Avoid duplicates
                if constant_name in text_constants:
                    continue

                text_constants[constant_name] = text

                # Determine if partial match needed
                if "sent to" in text.lower() or "up to" in text.lower():
                    code += f'    TEXT_{constant_name} = "{text.split()[0]} {text.split()[1]}"  # partial match\n'
                else:
                    code += f'    TEXT_{constant_name} = "{text}"\n'
            code += "\n"

        return code

    def _generate_init_method(self, class_name: str) -> str:
        """Generate __init__ method with platform detection."""
        return f'''    def __init__(self, driver, timeout: int = 10):
        """
        Initialize {class_name}.

        Args:
            driver: Appium WebDriver instance
            timeout: Default timeout for waits
        """
        super().__init__(driver, timeout)
        self.platform = driver.capabilities.get("platformName", "Android").lower()
        logger.info(f"{class_name} initialized (platform: {{self.platform}})")

'''

    def _generate_helper_methods(self) -> str:
        """Generate cross-platform helper methods."""
        return '''    # ========================================================================
    # CROSS-PLATFORM LOCATOR HELPERS — fastest strategy per platform
    # ========================================================================

    def _by_id(self, resource_id: str) -> tuple[str, str]:
        """Return (by, locator) for ID — works on both platforms.
        Android: resource-id → AppiumBy.ID
        iOS: accessibilityIdentifier → AppiumBy.ACCESSIBILITY_ID
        """
        if self.platform == "android":
            return (AppiumBy.ID, resource_id)
        return (AppiumBy.ACCESSIBILITY_ID, resource_id)

    def _by_text(self, text: str) -> tuple[str, str]:
        """Return (by, locator) for exact text match — fastest per platform.
        Android: UiAutomator2 (~0.3s)
        iOS: NSPredicate (~0.3s)
        """
        if self.platform == "android":
            return (AppiumBy.ANDROID_UIAUTOMATOR, f'new UiSelector().text("{text}")')
        return (AppiumBy.IOS_PREDICATE, f'label == "{text}"')

    def _by_text_contains(self, text: str) -> tuple[str, str]:
        """Return (by, locator) for partial text match — fastest per platform.
        Android: UiAutomator2 textContains
        iOS: NSPredicate CONTAINS
        """
        if self.platform == "android":
            return (AppiumBy.ANDROID_UIAUTOMATOR, f'new UiSelector().textContains("{text}")')
        return (AppiumBy.IOS_PREDICATE, f'label CONTAINS "{text}"')

'''

    def _generate_business_methods(
        self, screen_name: str, interactive: list[dict], display: list[dict]
    ) -> str:
        """Generate business methods for interactions."""
        code = ""

        # Generate wait_for_screen method
        code += self._generate_wait_for_screen_method(screen_name, display)

        # Generate tap methods for buttons
        code += self._generate_tap_methods(interactive)

        # Generate input methods for text fields
        code += self._generate_input_methods(interactive)

        return code

    def _generate_wait_for_screen_method(self, screen_name: str, display: list[dict]) -> str:
        """Generate wait_for_screen method."""
        # Pick 2-3 key display elements for screen detection
        key_elements = [elem for elem in display[:3] if elem.get("text", "").strip()]

        if not key_elements:
            return ""

        method_name = f"wait_for_{screen_name}_screen"

        code = f'''    def {method_name}(self, timeout: int = 15) -> "{self._to_class_name(screen_name)}":
        """
        Wait for {screen_name} screen to be fully loaded.

        Args:
            timeout: Maximum wait time in seconds (default: 15s)

        Returns:
            self for method chaining
        """
'''

        # Add required elements
        code += "        required_elements = [\n"
        for elem in key_elements:
            text = elem.get("text", "").strip()
            if text:
                code += f'            (*self._by_text("{text}"), "{text}"),\n'
        code += "        ]\n\n"

        code += f'''        self.wait_for_screen_ready(
            required_elements=required_elements,
            screen_name="{screen_name.title()} Screen",
            timeout=timeout
        )
        return self

'''
        return code

    def _generate_tap_methods(self, interactive: list[dict]) -> str:
        """Generate tap methods for buttons."""
        code = ""

        for elem in interactive:
            _elem_type = elem.get("type", "")
            text = elem.get("text", "").strip()
            constant = self._fix_constant_name(elem.get("constant", ""))

            # Only generate for buttons/clickable elements
            if "button" not in constant.lower():
                continue

            method_name = constant.lower().replace("_button", "").replace("_btn", "")
            action_text = text if text else "element"

            code += f'''    def tap_{method_name}(self) -> "BasePage":
        """Tap {action_text}."""
        by, locator = self._by_id(self.{constant})
        self.tap(locator, by)
        return self

'''

        return code

    def _generate_input_methods(self, interactive: list[dict]) -> str:
        """Generate input methods for text fields."""
        code = ""

        for elem in interactive:
            _elem_type = elem.get("type", "")
            constant = self._fix_constant_name(elem.get("constant", ""))

            # Only generate for input fields
            if "input" not in constant.lower() and "edit" not in constant.lower():
                continue

            field_name = constant.lower().replace("_input", "").replace("_edit", "")

            code += f'''    def enter_{field_name}(self, text: str) -> "BasePage":
        """Enter text into {field_name} field."""
        by, locator = self._by_id(self.{constant})
        self.input_text(locator, text, by)
        return self

'''

        return code

    # ========================================================================
    # UTILITY METHODS
    # ========================================================================

    def _fix_constant_name(self, name: str) -> str:
        """Fix invalid Python identifier names."""
        # Remove invalid characters
        name = re.sub(r"[^A-Z0-9_]", "_", name)

        # Fix names starting with numbers
        if name and name[0].isdigit():
            number_map = {
                "0": "ZERO",
                "1": "ONE",
                "2": "TWO",
                "3": "THREE",
                "4": "FOUR",
                "5": "FIVE",
                "6": "SIX",
                "7": "SEVEN",
                "8": "EIGHT",
                "9": "NINE",
            }
            name = number_map.get(name[0], "NUM") + "_" + name[1:]

        # Remove duplicate underscores
        name = re.sub(r"_+", "_", name)

        return name.strip("_")

    def _text_to_constant(self, text: str) -> str:
        """Convert display text to constant name."""
        # Clean text
        text = text.strip()

        # Remove special characters, keep alphanumeric and spaces
        text = re.sub(r"[^a-zA-Z0-9\s+]", " ", text)

        # Convert to uppercase and replace spaces with underscores
        constant = text.upper().replace(" ", "_").replace("+", "_PLUS_")

        # Remove duplicate underscores
        constant = re.sub(r"_+", "_", constant)

        return constant.strip("_")

    def _to_class_name(self, screen_name: str) -> str:
        """Convert screen name to PascalCase class name."""
        # Split by underscore or hyphen
        parts = re.split(r"[-_]", screen_name)
        # Capitalize each part
        class_name = "".join(p.capitalize() for p in parts)
        # Add Page suffix if not present
        if not class_name.endswith("Page"):
            class_name += "Page"
        return class_name

    def _smart_update_page_object(
        self, file_path: Path, interactive: list[dict], display: list[dict], platform: str
    ) -> str:
        """
        Smart update: Merge new locators with existing ones, preserve all business logic.

        Args:
            file_path: Path to existing page object file
            interactive: List of interactive elements from scan
            display: List of display elements from scan
            platform: Target platform

        Returns:
            Updated page object code
        """
        # Read existing file
        existing_code = file_path.read_text()

        # Find locator section boundaries
        locator_start_pattern = r"    # ={70,}\n    # LOCATOR DEFINITIONS"
        locator_end_pattern = r"    def __init__"

        # Try to find and merge locators section
        import re

        start_match = re.search(locator_start_pattern, existing_code)
        end_match = re.search(locator_end_pattern, existing_code)

        if start_match and end_match:
            # Extract existing locators section
            existing_locators_section = existing_code[start_match.end() : end_match.start()]

            # Parse existing locators
            existing_locators = self._parse_existing_locators(existing_locators_section)

            # Generate new locators from scan
            new_interactive_locators, new_display_locators = self._extract_new_locators(
                interactive, display, platform
            )

            # Merge: existing + new (new ones override if duplicate)
            merged_interactive = {**existing_locators["interactive"], **new_interactive_locators}
            merged_display = {**existing_locators["display"], **new_display_locators}

            # Rebuild locators section with merged data
            merged_locators_section = self._build_merged_locators_section(
                merged_interactive, merged_display
            )

            # Rebuild file
            before_locators = existing_code[: start_match.start()]
            after_locators = existing_code[end_match.start() :]

            # Add the header back
            locator_header = existing_code[start_match.start() : start_match.end()]
            updated_code = (
                before_locators + locator_header + merged_locators_section + after_locators
            )

            # Add update comment to docstring
            updated_code = self._add_update_timestamp(updated_code)

            # Count new vs existing
            new_count = len(new_interactive_locators) + len(new_display_locators)
            existing_count = len(existing_locators["interactive"]) + len(
                existing_locators["display"]
            )
            total_count = len(merged_interactive) + len(merged_display)

            print(
                f"  ✓ Locators merged: {existing_count} existing + {new_count} new = {total_count} total"
            )
            print("  ✓ Business methods preserved")
            return updated_code

        else:
            # Fallback: Try to parse manually-written file
            print("  ⚠️  Could not locate structured section markers")
            print("  ℹ️  Attempting smart merge with manually-written file...")

            try:
                updated_code = self._merge_with_manual_file(
                    existing_code, interactive, display, platform
                )
                print("  ✓ Successfully merged with existing locators")
                print("  ✓ Preserved all custom business logic")
                return updated_code
            except Exception as e:
                # Last resort: Show error and return original code unchanged
                print(f"  ❌ Merge failed: {e}")
                print("  ⚠️  File left UNCHANGED to prevent data loss")
                print("  ⚠️  Manual merge required or use --force to regenerate")
                return existing_code  # Return original, don't destroy!

    def _merge_with_manual_file(
        self, existing_code: str, interactive: list[dict], display: list[dict], platform: str
    ) -> str:
        """
        Merge new locators with a manually-written file.

        This handles files that don't have structured section markers.
        Extracts existing locators, merges with new ones, inserts at safe location.

        Args:
            existing_code: Content of existing file
            interactive: List of interactive elements from scan
            display: List of display elements from scan
            platform: Target platform

        Returns:
            Updated code with merged locators
        """
        import re

        # Find class definition
        class_match = re.search(r'(class \w+\(BasePage\):.*?""".*?""")', existing_code, re.DOTALL)
        if not class_match:
            raise ValueError("Could not find class definition")

        # Find __init__ method
        init_match = re.search(r"(\n    def __init__)", existing_code)
        if not init_match:
            raise ValueError("Could not find __init__ method")

        # Extract everything between class docstring and __init__
        existing_locators_section = existing_code[class_match.end() : init_match.start()]

        # Parse existing locators (any format)
        existing_locators = self._parse_manual_locators(existing_locators_section)

        # Extract new locators from scan
        new_interactive_locators, new_display_locators = self._extract_new_locators(
            interactive, display, platform
        )

        # Merge: Keep existing, add new (new ones override if duplicate)
        merged_interactive = {**existing_locators["interactive"], **new_interactive_locators}
        merged_display = {**existing_locators["display"], **new_display_locators}

        # Build new structured locators section
        merged_section = self._build_merged_locators_section(merged_interactive, merged_display)

        # Add structured header
        from datetime import datetime

        structured_header = f"""

    # ============================================================================
    # LOCATOR DEFINITIONS — Cross-platform, fast (NO XPath!)
    # Auto-generated from live device scan on {datetime.now().strftime("%Y-%m-%d")}
    #
    # ID-based locators: work on both Android (ID) and iOS (Accessibility ID)
    # Text constants: converted to UiAutomator2 (Android) or NSPredicate (iOS)
    #                 at runtime via _by_text() / _by_text_contains() helpers
    # ============================================================================
"""

        # Check if file has helper methods
        has_helpers = bool(re.search(r"def _by_id\(", existing_code))

        # Rebuild file: class definition + new structured section + helpers (if needed) + rest
        before_locators = existing_code[: class_match.end()]
        after_locators = existing_code[init_match.start() :]

        # Add helper methods if they don't exist
        helpers_section = ""
        if not has_helpers:
            helpers_section = '''
    # ========================================================================
    # CROSS-PLATFORM HELPER METHODS
    # These convert locators to platform-specific formats at runtime
    # ========================================================================

    def _by_id(self, resource_id: str) -> tuple[str, str]:
        """
        Cross-platform ID locator.

        Android: Uses AppiumBy.ID
        iOS: Uses AppiumBy.ACCESSIBILITY_ID

        Args:
            resource_id: The resource-id (Android) or accessibility-id (iOS)

        Returns:
            Tuple of (AppiumBy strategy, locator value)
        """
        if self.platform == "android":
            return (AppiumBy.ID, resource_id)
        return (AppiumBy.ACCESSIBILITY_ID, resource_id)

    def _by_text(self, text: str) -> tuple[str, str]:
        """
        Cross-platform exact text match.

        Android: Uses UiAutomator2 with text() selector
        iOS: Uses NSPredicate with label == "text"

        Args:
            text: The exact text to match

        Returns:
            Tuple of (AppiumBy strategy, locator value)
        """
        if self.platform == "android":
            return (AppiumBy.ANDROID_UIAUTOMATOR, f'new UiSelector().text("{text}")')
        return (AppiumBy.IOS_PREDICATE, f'label == "{text}"')

    def _by_text_contains(self, text: str) -> tuple[str, str]:
        """
        Cross-platform partial text match.

        Android: Uses UiAutomator2 with textContains() selector
        iOS: Uses NSPredicate with CONTAINS modifier

        Args:
            text: The partial text to match

        Returns:
            Tuple of (AppiumBy strategy, locator value)
        """
        if self.platform == "android":
            return (AppiumBy.ANDROID_UIAUTOMATOR, f'new UiSelector().textContains("{text}")')
        return (AppiumBy.IOS_PREDICATE, f'label CONTAINS "{text}"')

'''

        updated_code = (
            before_locators + structured_header + merged_section + helpers_section + after_locators
        )

        return updated_code

    def _parse_manual_locators(self, locators_section: str) -> dict:
        """
        Parse locators from manually-written file (any format).

        Extracts all UPPERCASE_CONSTANTS = "value" from the section.

        Args:
            locators_section: The section containing locator definitions

        Returns:
            Dict with 'interactive' and 'display' locators
        """
        import re

        interactive = {}
        display = {}

        # Pattern matches: CONSTANT_NAME = "value" or CONSTANT_NAME = 'value'
        # Handles nested quotes like: "//*[@text='Consultation']"
        # Uses non-greedy match with escaped quote handling

        # Try double-quoted strings first (most common)
        pattern_double = r'([A-Z][A-Z0-9_]*)\s*=\s*"([^"\\]*(?:\\.[^"\\]*)*)"'
        for match in re.finditer(pattern_double, locators_section):
            name, value = match.groups()
            if name.startswith("TEXT_"):
                display[name] = value
            else:
                interactive[name] = value

        # Then try single-quoted strings
        pattern_single = r"([A-Z][A-Z0-9_]*)\s*=\s*'([^'\\]*(?:\\.[^'\\]*)*)'"
        for match in re.finditer(pattern_single, locators_section):
            name, value = match.groups()
            # Only add if not already captured
            if name not in interactive and name not in display:
                if name.startswith("TEXT_"):
                    display[name] = value
                else:
                    interactive[name] = value

        return {"interactive": interactive, "display": display}

    def _parse_existing_locators(self, locators_section: str) -> dict:
        """
        Parse existing locators from file into a dict.

        Returns:
            {'interactive': {name: value, ...}, 'display': {name: value, ...}}
        """
        interactive = {}
        display = {}

        # Parse lines like: BUTTON_NAME = "value" or TEXT_NAME = "value"
        import re

        for line in locators_section.split("\n"):
            line = line.strip()
            if not line or line.startswith("#"):
                continue

            # Match: CONSTANT_NAME = "value"
            match = re.match(r'([A-Z_0-9]+)\s*=\s*["\'](.+)["\']', line)
            if match:
                name, value = match.groups()
                # Categorize by prefix
                if name.startswith("TEXT_"):
                    display[name] = value
                else:
                    interactive[name] = value

        return {"interactive": interactive, "display": display}

    def _extract_new_locators(
        self, interactive: list[dict], display: list[dict], platform: str
    ) -> tuple[dict, dict]:
        """
        Extract locators from scan results into dicts.

        Returns:
            (interactive_dict, display_dict)
        """
        interactive_dict = {}
        display_dict = {}

        # Extract interactive elements (ID-based)
        for elem in interactive:
            locator_type = elem.get("locator_type", "")
            locator_value = elem.get("locator", "")
            constant_name = elem.get("constant", "UNKNOWN")

            # Fix invalid Python identifiers
            constant_name = self._fix_constant_name(constant_name)

            if locator_type == "ID" or "resource-id" in locator_value:
                # Extract ID value
                if "'" in locator_value:
                    id_value = locator_value.split("'")[1]
                else:
                    id_value = locator_value
                interactive_dict[constant_name] = id_value

        # Extract display elements (text-based)
        for elem in display:
            text = elem.get("text", "").strip()
            if not text or text in ["", "\\ue3c9", "\\ue1b0"]:  # Skip empty/icon texts
                continue

            # Create constant name from text
            constant_name = "TEXT_" + self._text_to_constant(text)
            constant_name = self._fix_constant_name(constant_name)

            # Skip if already exists (avoid duplicates)
            if constant_name in display_dict:
                continue

            display_dict[constant_name] = text

        return interactive_dict, display_dict

    def _build_merged_locators_section(self, interactive: dict, display: dict) -> str:
        """Build locators section from merged dicts."""
        code = "\n"

        # Interactive elements section
        if interactive:
            code += (
                "    # --- Interactive Elements (by resource-id — works on BOTH platforms) ---\n"
            )
            for name, value in sorted(interactive.items()):
                code += f'    {name} = "{value}"\n'
            code += "\n"

        # Display text section
        if display:
            code += (
                "    # --- Text constants (plain strings — converted per platform by helpers) ---\n"
            )
            for name, value in sorted(display.items()):
                code += f'    {name} = "{value}"\n'
            code += "\n"

        return code

    def _add_update_timestamp(self, code: str) -> str:
        """Add update timestamp to file docstring."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

        # Add update line to docstring
        if '"""' in code:
            parts = code.split('"""', 2)
            if len(parts) >= 2:
                docstring = parts[1]
                # Add update notice if not already there
                if "Last updated:" not in docstring:
                    docstring += f"\n\nLast updated: {timestamp} (locators refreshed)\n"
                else:
                    # Replace existing timestamp
                    docstring = re.sub(
                        r"Last updated: .*",
                        f"Last updated: {timestamp} (locators refreshed)",
                        docstring,
                    )
                parts[1] = docstring
                return '"""'.join(parts)

        return code

    def _generate_full_code(
        self,
        screen_name: str,
        class_name: str,
        interactive: list[dict],
        display: list[dict],
        platform: str,
    ) -> str:
        """Generate complete page object code (used as fallback)."""
        code = self._generate_header(screen_name, class_name, len(interactive), len(display))
        code += self._generate_imports()
        code += self._generate_class_definition(class_name)
        code += self._generate_screen_timing()
        code += self._generate_locators(interactive, display, platform)
        code += self._generate_init_method(class_name)
        code += self._generate_helper_methods()
        code += self._generate_business_methods(screen_name, interactive, display)
        return code
